[package]
name = "encrypted-ixs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
arcis-imports = "0.3.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
